apps:
  - script: ./lib/ChildProcess/esmTransferMeasurementToFIPHR.js
    name: 'fiphr_services'
    watch: true
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
  - script: ./lib/ChildProcess/esmTransferMeasurementToFIPHR.js
    name: 'fiphr_services_2'
    watch: true
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
